# Generated by Django 2.1.7 on 2019-02-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190224_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerschool',
            name='time_left',
            field=models.DateField(null=True),
        ),
    ]
