# Generated by Django 2.1.7 on 2019-02-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190224_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerschool',
            name='title',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
