# Generated by Django 2.1.7 on 2019-02-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('person_father_name', models.CharField(max_length=100)),
                ('person_mother_name', models.CharField(max_length=100)),
                ('person_email', models.EmailField(max_length=254)),
                ('person_phone_number', models.IntegerField()),
                ('person_message', models.TextField()),
            ],
        ),
    ]
